Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -117,9 +117,11 @@ jobs:
 
       - name: Simulate Failure for Alert Testing
         run: |
-          export STEP_NAME="Simulate Failure for Alert Testing"
-          echo "Simulating failure to test alert notifications..."
-          exit 1
+         export STEP_NAME="Simulate Failure for Alert Testing"
+         source userscripts/notify_sns_failure.sh
+         echo "Simulating failure to test alert notifications..."
+         exit 1
+
 
       - name: Terraform Apply & Capture Output
         env:
