Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -109,6 +109,11 @@ jobs:
         run: terraform plan -var-file=${{ env.TFVARS_FILE }} -var="ec2_ssh_private_key=${EC2_SSH_PRIVATE_KEY}" -out=tfplan
         working-directory: ./Terraform # Ensure this is explicitly set for clarity
 
+      - name: Simulate Failure for Alert Testing
+        run: |
+           echo "Simulating failure to test alert notifications..."
+           exit 1 
+      
       - name: Terraform Apply & Capture Output
         env:
           EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
